import type { MemberCardModel } from "@/lib/members/types";

/** Shown only when Supabase read env is not configured (local demo). */
export const MOCK_MEMBER_CARDS: MemberCardModel[] = [
  {
    id: "mock-1",
    name: "Metasal",
    title: "Founder",
    company: null,
    skills: ["DevRel", "Product"],
    photoUrl: "/builders_images/1.jpg",
    twitterUrl: "https://x.com/metasal",
  },
  {
    id: "mock-2",
    name: "Jordan Lee",
    title: "Core Contributor",
    company: "Superteam",
    skills: ["Engineering", "Community"],
    photoUrl: "/builders_images/2.jpg",
    twitterUrl: "https://x.com/jordanl",
  },
  {
    id: "mock-3",
    name: "Samira Okafor",
    title: "Product Lead",
    company: null,
    skills: ["Product", "Design"],
    photoUrl: "/builders_images/3.jpg",
    twitterUrl: "https://x.com/samiraok",
  },
  {
    id: "mock-4",
    name: "Chris Patel",
    title: "Developer Advocate",
    company: null,
    skills: ["DevRel", "Education"],
    photoUrl: "/builders_images/4.jpg",
    twitterUrl: "https://x.com/chrisp",
  },
  {
    id: "mock-5",
    name: "Alex Nguyen",
    title: "Ecosystem",
    company: null,
    skills: ["Partnerships", "Growth"],
    photoUrl: "/builders_images/5.jpg",
    twitterUrl: "https://x.com/alexng",
  },
  {
    id: "mock-6",
    name: "Riley Kim",
    title: "Operations",
    company: null,
    skills: ["Events", "Programs"],
    photoUrl: "/builders_images/6.jpg",
    twitterUrl: "https://x.com/rileyk",
  },
  {
    id: "mock-7",
    name: "Taylor Singh",
    title: "Institutions",
    company: null,
    skills: ["Policy", "Research"],
    photoUrl: "/builders_images/7.jpg",
    twitterUrl: "https://x.com/taylors",
  },
];
